from ares.sources.Toy import Toy
from ares.sources.Star import Star
from ares.sources.StarQS import StarQS
from ares.sources.Toy import DeltaFunction
from ares.sources.BlackHole import BlackHole
from ares.sources.Composite import Composite
from ares.sources.SynthesisModel import SynthesisModel
from ares.sources.SynthesisModelToy import SynthesisModelToy
from ares.sources.SynthesisModelSBS import SynthesisModelSBS
from ares.sources.SynthesisModelHybrid import SynthesisModelHybrid
