from ares.sources.Toy import Toy
from ares.sources.Star import Star
from ares.sources.StarQS import StarQS
from ares.sources.Galaxy import Galaxy
from ares.sources.Diffuse import Diffuse
from ares.sources.Toy import DeltaFunction
from ares.sources.BlackHole import BlackHole
from ares.sources.Composite import Composite
from ares.sources.SynthesisModel import SynthesisModel
